### ISSUE TITLE
[FEATURE] Please allow the window to be resized.

### ISSUE THREAD

**Issue by k-electron** [OhMyGuus/BetterCrewLink#285] opened 2021-11-30 02:07 UTC
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)
- [X] My feature request is not one of the **commonly suggested features**: iOS app (it's already being development)

### Is your feature request related to a problem? Please describe.

The window size being locked to a really tiny size makes it very hard to use. This is especially frustrating for the settings screen where it would be really helpful to see all settings at once.

### Describe the solution you'd like

Allow the window size to be resized.

### Describe alternatives you've considered

no alternatives really.

**Comment by MatadorProBr** [comment] 2021-11-30 03:12
Duplicate of #52

**Closed as completed by MatadorProBr** 2021-11-30 03:12 UTC
Labels: Enhancement
