### ISSUE TITLE
[BUG REPORT] "invisible" users can join of sorts

### ISSUE THREAD

**Issue by Hanabanashii** [OhMyGuus/BetterCrewLink#287] opened 2022-01-03 03:25 UTC
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

I've had some cases where a "ghost" user ends up in the voice server, they do not show up as a player and can be heard globally, they don't show up in the player list so you can't mute them/change their volume. There must be a trick to do this, 'cause it's deliberately done to mic spam without any repercussion and if anyone has an idea of how to replicate this that'd be nice.

### Steps to reproduce the behavior

Unfortunately, I don't know personally how to do this (doubt the perpetrators would share how they did anyways)

### Expected behavior

Uhh, they'd be able to be seen in the player list? 

### Desktop

- OS: Windows 10
- Version: 2.9.1

**Comment by MatadorProBr** [comment] 2022-01-03 14:33
If this is really true, it could be the end of public lobbies and to try to fix the problem we will need the steps of how to reproduce this bug because without then, it will be more hard to fix the problem

I will ask you some questions so maybe this will help on the fix of the bug:

1. Are you sure does this have to do with BCL? Like: you are in a Discord call with other people that are using BCL too and some people started making mic spam on the Discord call (not in BCL).

2. These users appeared in Among Us? On the match, at emergency meetings and in the lobby?

3. You think that they are using hacks? Not in BCL but in Among Us since theres some ways that you can make a player join and the player doesn't show up at match, meetings and lobby like he doesn't exist but he's there.

**Comment by OhMyGuus** [comment] 2022-01-03 16:06
Thanks for the report.
I know of the issue with able to hear someone when they aren't in the lobby anymore so that will be fixed asap (this might be already resolved with the commit I just did or its the actual function that isn't working need to test it still) 

This won't fix the full issue (since they can still bypass this pretty easy) however but I will think of a real solution this week. 

Sadly but honest I kind of already knew this was possible going to happen because of the way bcl is build, basically the authentication to the lobby is the lobby code, The sad thing is with public lobbies is that the lobby code is basically public as well.

**Comment by Hanabanashii** [comment] 2022-01-03 20:58
I'm sure they're not from Discord, it was in a public lobby and everyone hears them. I don't think they're using hacks though as the game itself isn't really affected negatively, no ghost user ingame or the like..

If there was a way to see clients directly for the host maybe that'd help, idk  how that's handled but if it can see those that the game doesn't have it could go past whatever they're doing

**Comment by MatadorProBr** [comment] 2022-01-04 01:10
I will send the download of the last commit to the "temporary fix" if anyone wants

Windows: https://nightly.link/OhMyGuus/BetterCrewLink/suites/4818099229/artifacts/135798207
Linux: https://nightly.link/OhMyGuus/BetterCrewLink/suites/4818099229/artifacts/135798206

**Comment by MatadorProBr** [comment] 2022-03-06 14:43
Also I will close this issue since it's "temporary fixed", if this happens again, just open the issue

**Closed as completed by MatadorProBr** 2022-03-06 14:43 UTC
Labels: Bug Report, Help Wanted, Priority: High, Confirmed Bug
